# Site settings
title: Adam Jaamour
description: My personal programming website, including my programming experiences, education, past jobs, contact details, and more.
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
# baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Adam Jaamour
user_title: Software Engineer
email: adam@jaamour.com

# Global settings
icon_size: 58

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
