# Site settings
title: Adam Jaamour
description: Adam Jaamour's portfolio of past and ongoing work, includes publications, projects, open-source projects, recommended readings, stackoverflow contributions and more.
url: "https://adam.jaamour.com/" # the base hostname & protocol for your site
# baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Adam Jaamour
email: hello@jaamour.com

# Global settings
icon_size: 58

exclude: [vendor]

# Google Analytics tracking ID
google_analytics_tracking_id: G-8HMF4KN8GS