# Site settings
title: Adam Jaamour
description: My personal programming website, including my programming experiences, education, past jobs, contact details, and more.
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
# baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Adam Jaamour
user_description: I'm a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT.. I'm one of the two guys behind all the JS related stuff. Visit my blog here":" <a href="https://mauriciourraco.com" target="_blank">https://mauriciourraco.com</a>
user_title: Software Engineer
email: adam@jaamour.com

# Global settings
icon_size: 58

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
